### ISSUE TITLE
RoachPHP cant guess correct charset for response

### ISSUE THREAD

**Issue by grzegorzbogusz** [Plan-Zajec-PZ/API#24]
RoachPHP guess charset of response as UTF-8 which isn't correct since polish special characters ends up as `?`

**Comment by MrHDOLEK** [comment]
@grzegorzbogusz should help https://www.php.net/manual/en/function.utf8-encode.php

**Comment by grzegorzbogusz** [comment]
> @grzegorzbogusz should help https://www.php.net/manual/en/function.utf8-encode.php

That doesn't work as an original string is encoded with ISO-8859-2 and the `utf8_encode` method assumes its ISO-8859-1, but we found a similar workaround with the `iconv` method. Thanks for the help, appreciate it!
